### ISSUE TITLE
utf8conf build error

### ISSUE THREAD

**Issue by blindpet** [comotion/VSF#23]
Trying to build with Varnish 4.1 and getting this error, instructions are the same as I used last time I tested
```
make  all-recursive
make[1]: Entering directory '/root/VSF/libvmod-vsf'
Making all in src
make[2]: Entering directory '/root/VSF/libvmod-vsf/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -I/usr/include/varnish -I../utf8proc -g -O2 -MT libvmod_vsf_la-vmod_vsf.lo -MD -MP -MF .deps/libvmod_vsf_la-vmod_vsf.Tpo -c -o libvmod_vsf_la-vmod_vsf.lo `test -f 'vmod_vsf.c' || echo './'`vmod_vsf.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -I../utf8proc -g -O2 -MT libvmod_vsf_la-vmod_vsf.lo -MD -MP -MF .deps/libvmod_vsf_la-vmod_vsf.Tpo -c vmod_vsf.c  -fPIC -DPIC -o .libs/libvmod_vsf_la-vmod_vsf.o
vmod_vsf.c:60:22: fatal error: utf8proc.h: No such file or directory
 #include <utf8proc.h>
                      ^
compilation terminated.
Makefile:638: recipe for target 'libvmod_vsf_la-vmod_vsf.lo' failed
make[2]: *** [libvmod_vsf_la-vmod_vsf.lo] Error 1
make[2]: Leaving directory '/root/VSF/libvmod-vsf/src'
Makefile:453: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
```

**Comment by fgsch** [comment]
Please provide the whole make output and also the output of `git branch -v`.

**Comment by blindpet** [comment]
Git branch

    root@htpcguides:~/VSF/libvmod-vsf# git branch -v
    * master be2d4ec build status, rst version

That is the whole make output

´´´
:~/VSF/libvmod-vsf# make
make  all-recursive
make[1]: Entering directory '/root/VSF/libvmod-vsf'
Making all in src
make[2]: Entering directory '/root/VSF/libvmod-vsf/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -I/usr/include/varnish -I../utf8proc -g -O2 -MT libvmod_vsf_la-vmod_vsf.lo -MD -MP -MF .deps/libvmod_vsf_la-vmod_vsf.Tpo -c -o libvmod_vsf_la-vmod_vsf.lo `test -f 'vmod_vsf.c' || echo './'`vmod_vsf.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -I../utf8proc -g -O2 -MT libvmod_vsf_la-vmod_vsf.lo -MD -MP -MF .deps/libvmod_vsf_la-vmod_vsf.Tpo -c vmod_vsf.c  -fPIC -DPIC -o .libs/libvmod_vsf_la-vmod_vsf.o
vmod_vsf.c:60:22: fatal error: utf8proc.h: No such file or directory
 #include <utf8proc.h>
                      ^
compilation terminated.
Makefile:638: recipe for target 'libvmod_vsf_la-vmod_vsf.lo' failed
make[2]: *** [libvmod_vsf_la-vmod_vsf.lo] Error 1
make[2]: Leaving directory '/root/VSF/libvmod-vsf/src'
Makefile:453: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/VSF/libvmod-vsf'
Makefile:363: recipe for target 'all' failed
make: *** [all] Error 2
´´´

**Comment by comotion** [comment]
hello.
the build instructions have been changed and simplified in a recent commit;
The problem is that you haven't inited the git submodule; however the toplevel makefile does this for you.
you should now go to the VSF toplevel (one path above libvmod-vsf) and type make.

This will check out the git submodules utf8proc and build everything.

**Comment by blindpet** [comment]
Thank you all built and working now. I will update my own instructions too.

It will be nice when it is sudo apt-get install libvmod-vsf ;)

**Comment by comotion** [comment]
agreed. we'll get there
